# Generated by Django 5.0 on 2023-12-14 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
