# Generated by Django 5.0 on 2023-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_todoitem_due_date_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
