# Generated by Django 5.0 on 2023-12-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_todoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('Pending', 'Pending'), ('completed', 'Completed')], max_length=20),
        ),
    ]
