# Generated by Django 5.0 on 2023-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo_images/'),
        ),
    ]
